<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="5_wheel_bot">

  <xacro:property name="base_width" value="1" />
  <xacro:property name="base_len" value="0.6" />
  <xacro:property name="base_height" value="0.2" />
  <xacro:property name="wheel_len" value="0.1" />
  <xacro:property name="wheel_radius" value="0.035" />
  <xacro:property name="pi" value="3.1415" />

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
<material name="black">
    <color rgba="0 0 0 1"/>
</material>

<link name="base_link">
    <visual>
      <geometry>
        <box size="${base_len} ${base_width} ${base_height}"/>
      </geometry>
      <material name="white"/>
    </visual>
</link>

<link name="front_wheel">
    <visual>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
<origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
</link>

  <joint name="front_wheel_joint" type="continuous">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="front_wheel"/>
    <origin rpy="0 0 0" xyz="${base_len/2-wheel_radius} 0 -${base_height/2+wheel_radius}"/>
  </joint>

<link name="right_front_wheel">
    <visual>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>

    </visual>
</link>

  <joint name="right_front_wheel_joint" type="continuous">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="right_front_wheel"/>
    <origin rpy="0 0 0" xyz="${base_len/2-wheel_radius-wheel_len} -${base_width/2-wheel_len/2} -${base_height/2+wheel_radius}"/>
  </joint>


<link name="right_back_wheel">
    <visual>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
</link>

  <joint name="right_back_wheel_joint" type="continuous">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="right_back_wheel"/>
    <origin rpy="0 0 0" xyz="-${base_len/2-wheel_radius-wheel_len} -${base_width/2-wheel_len/2} -${base_height/2+wheel_radius}"/>
  </joint>

<link name="left_front_wheel">
    <visual>
      <origin rpy="1.57075 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
</link>

  <joint name="left_front_wheel_joint" type="continuous">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="left_front_wheel"/>
    <origin rpy="0 0 0" xyz="${base_len/2-wheel_radius-wheel_len} ${base_width/2-wheel_len/2} -${base_height/2+wheel_radius}"/>
  </joint>


<link name="left_back_wheel">
    <visual>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
</link>

  <joint name="left_back_wheel_joint" type="continuous">
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <parent link="base_link"/>
    <child link="left_back_wheel"/>
    <origin rpy="0 0 0" xyz="-${base_len/2-wheel_radius-wheel_len} ${base_width/2-wheel_len/2} -${base_height/2+wheel_radius}"/>
  </joint>
<link name="base_footprint">
</link>
<joint name="footprint_base" type="fixed">
<parent link="base_footprint"/>
<child link="base_link"/>
<origin xyz="0 0 ${base_height/2+(wheel_radius*2)}" rpy="0 0 0"/>
</joint>
</robot>
